// ============================================================================
// generate_sample_outputs.sce -- regenerates the sample result files from
// real engine runs (no hard-coded numbers).
//
// Run from this folder:  scilab-cli -nb -f generate_sample_outputs.sce
// Writes (overwrites ONLY these generated names) into outputs/:
//   sample_outputs.txt                        all datasets x models + comparison
//   sample_prediction.csv                     Linear Regression, Tech Growth
//   sample_backtest.csv                       same + backtest vs buy & hold
//   sample_prediction_exponential_smoothing.csv
//   sample_comparison.txt                     comparison, ranking, walk-forward
// ============================================================================
clear; clc;
APP_DIR = get_absolute_file_path("generate_sample_outputs.sce");
exec(APP_DIR + "model_engine.sce", -1);

out_dir = APP_DIR + "outputs/";
if ~isdir(out_dir) then mkdir(out_dir); end

files = ["sample_data/tech_growth_stock.csv", "sample_data/blue_chip_stock.csv", "sample_data/volatile_stock.csv"];
names = ["Tech Growth Stock (synthetic)", "Blue Chip Stock (synthetic)", "Volatile Stock (synthetic)"];
cfg = struct("split_ratio", 0.8, "ar_lookback", 10, "es_alpha", 0.3, "es_beta", 0.1, "n_folds", 5, ..
             "buy", 0.5, "sell", -0.5, "cost", 0.1, "slip", 0.05, "capital", 100000);

summary = ["StockVision sample outputs (generated by generate_sample_outputs.sce)"; ..
           "Settings: split 80/20, AR lookback 10, ES alpha 0.3 beta 0.1, 5 WF folds,"; ..
           "BUY >= +0.5%, SELL <= -0.5%, cost 0.1%, slippage 0.05%, capital 100000."; ..
           "All numbers below come from actual runs; synthetic data, not financial advice."; " "];
comparison_txt = ["MODEL COMPARISON, RANKING AND WALK-FORWARD (all bundled datasets)"; ..
                  "Generated by generate_sample_outputs.sce from real runs."; " "];

for i = 1:3
    data = load_dataset(APP_DIR + files(i));
    rep = build_report_struct(names(i), data, cfg, "LR", %t);
    cmp = rep.cmp;

    summary = [summary; "=== " + names(i) + " ==="; ..
               "Rows: " + string(data.n) + "   Test window: " + string(cmp.results(1).n_test) + " rows"; ..
               format_comparison(cmp); format_ranking(cmp); " "];
    comparison_txt = [comparison_txt; "==== " + names(i) + " ===="; format_comparison(cmp); " "; ..
                      format_ranking(cmp); " "; "Walk-forward:"; format_walk_forward(cmp.wf); " "];

    if i == 1 then
        // Single-model exports for the primary sample dataset.
        export_results_csv(out_dir + "sample_prediction.csv", build_report_struct(names(i), data, cfg, "LR", %f));
        export_results_csv(out_dir + "sample_backtest.csv", rep);
        export_results_csv(out_dir + "sample_prediction_exponential_smoothing.csv", build_report_struct(names(i), data, cfg, "ES", %f));
        summary = [summary; "Backtest (LR, Tech Growth):"; format_backtest(rep.bt, rep.analysis.name); " "];
    end
end

write_lines(out_dir + "sample_outputs.txt", summary);
write_lines(out_dir + "sample_comparison.txt", comparison_txt);
mprintf("Sample outputs written to %s\n", out_dir);
